sudo: required
language: java
jdk: oraclejdk11

services:
  - postgresql

before_install:
  - chmod +x mvnw

addons:
  sonarcloud:
  organization: "matijapojatar"
  token: $SONAR_TOKEN

script:
  - ./mvnw clean install -DskipTests=true -B
  - ./mvnw sonar:sonar -Dsonar.projectKey=$PROJECT_KEY -Dsonar.organization=matijapojatar -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN

dist: trusty

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: mrsisa-t14-deployment